import "./globals.css";
import Header from "./layout/header";
import Footer from "./layout/footer";

export const metadata = {
  title: "InvestEdge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="content">
        <Header />
        <main className="max-screen">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
